# A script for my fork of
# glucometerUtils (https://github.com/pat-nel87/glucometerutils/tree/customFeatures)
# Designed to work with output generated by --text argument added to dump
# Cleans up Data in txt file and allows search by datetime filtering
# tested with freestyle precisionNeo driver only 
#

import matplotlib
import matplotlib.pyplot as plt

from datetime import date, time, datetime


#globals
allReadings = []
dates = []
times = []
bloodSugar = []
        
def fileClean():

    file = input("Enter Filename: ")

    edit = open(file, "r")
    edit.seek(0,0)

    for line in edit:
        lin = edit.readline()
    
        try:
            reading = [lin[1]]

            for i in range(2,11):
                reading[0] = reading[0] + lin[i]
        
            dates.append(reading[0])
            reading.append(lin[12])

            for i in range(13,20):
                reading[1] = reading[1] + lin[i]
        
            times.append(reading[1])
            reading.append(lin[23])

            for i in range(24,28):
                reading[2] = reading[2] + lin[i]
        
            bloodSugar.append(reading[2])
        
            allReadings.append(reading)
    
        except IndexError:
            print("Processing Completed")
            break

def filterList(myList):
    
    # creates new list of lists with 2 indices
    # myList[n][0] datetime object
    # myList[n][1] blood glucose reading
    
    tempList = []
    
    for i in range(len(myList)):
        tempDate = date.fromisoformat(str(myList[i][0]))
        tempTime = time.fromisoformat(str(myList[i][1]))
        tempDateTime = datetime.combine(tempDate, tempTime)
        tempList.append([tempDateTime, myList[i][2]])
        #print(tempList[i])
    
    return tempList

def preciseFilter(filterList):
    # will filter by datetime
    print("Please Select a Filtering Parameter", "\n",
                "1: Year", "\n", "2: Month", "\n", "3: Day", "\n")
    choice = input(":---> ")
    choice = int(choice)
    
    if choice == 1:
        
        myYear = input("Enter a year: ")
        
        for i in range(len(filterList)):
            if filterList[i][0].year == int(myYear):
                print(filterList[i])

    elif choice == 2:
        
        myMonth = input("Enter a month: ")
        
        for i in range(len(filterList)):
            if filterList[i][0].month == int(myMonth):
                print(filterList[i])
    
    elif choice == 3:
        
        myYear = input("Enter Year: ")
        myMonth = input("Enter Month: ")
        myDay = input("Enter Day: ")
        
        for i in range(len(filterList)):
            if filterList[i][0].year == int(myYear):
                if filterList[i][0].month == int(myMonth):
                    if filterList[i][0].day == int(myDay):
                        print(filterList[i])

fileClean()
filtered = filterList(allReadings)
preciseFilter(filtered)






    

